### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KarolisSerp** [karstenw/FileMaker-DDR-Splitter#1]
Very usefull tool for getting git differences in Filemaker files. But we have an issue with DDR spliter. For first two DDRs it worked well and still working well but for the last versions of our file it is not working. Our solution is quite big we cant find what is wrong.
DDR splitter returns the error message:
EXCEPTION: 'not well-formed (invalid token): line 441645, column 155'
Failed parsing '/PathTO/file.xml'
How to fix it?

**Comment by karstenw** [comment]
That means that the DDR is not well formed.

There is no easy remedy for that.

1. Fix the XML with a text editor. That means loosing some data. You should know how the DDR-XML is supposed to look like and how XML works.

or 

2. Identify the Filemaker Object that generates the error and rebuild that object or delete it.
